version: '3.1'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./dockerData/dbData:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
  db_test:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_TEST}
    ports:
      - 5433:5432
  adminer:
    depends_on:
      - db
      - db_test
    image: adminer
    restart: always
    ports:
      - 8090:8080
